// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Pet - A pet for sale in the pet store
type Pet struct {
	Id int64 `json:"id,omitempty"`
	Category Category `json:"category,omitempty"`
	Name string `json:"name"`
	PhotoUrls []string `json:"photoUrls"`
	Tags []Tag `json:"tags,omitempty"`
	Status string `json:"status,omitempty"`
}
