//
// EnumClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum EnumClass: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case abc = "_abc"
    case efg = "-efg"
    case xyz = "(xyz)"
    // This case is a catch-all generated by OpenAPI such that the enum is "non-frozen".
    // If new enum cases are added that are unknown to the spec/client, they are safely
    // decoded to this case. The raw value of this case is a dummy value that attempts
    // to avoids collisions with previously specified cases.
    case unknownDefaultOpenAPI = "unknown_default_open_api"
}
