/*
OpenAPI Petstore

This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package petstore

import (
	"encoding/json"
)

// checks if the ArrayTestWithWrappedAndName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArrayTestWithWrappedAndName{}

// ArrayTestWithWrappedAndName struct for ArrayTestWithWrappedAndName
type ArrayTestWithWrappedAndName struct {
	ArrayOfString []string `json:"array_of_string,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ArrayTestWithWrappedAndName ArrayTestWithWrappedAndName

// NewArrayTestWithWrappedAndName instantiates a new ArrayTestWithWrappedAndName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArrayTestWithWrappedAndName() *ArrayTestWithWrappedAndName {
	this := ArrayTestWithWrappedAndName{}
	return &this
}

// NewArrayTestWithWrappedAndNameWithDefaults instantiates a new ArrayTestWithWrappedAndName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArrayTestWithWrappedAndNameWithDefaults() *ArrayTestWithWrappedAndName {
	this := ArrayTestWithWrappedAndName{}
	return &this
}

// GetArrayOfString returns the ArrayOfString field value if set, zero value otherwise.
func (o *ArrayTestWithWrappedAndName) GetArrayOfString() []string {
	if o == nil || IsNil(o.ArrayOfString) {
		var ret []string
		return ret
	}
	return o.ArrayOfString
}

// GetArrayOfStringOk returns a tuple with the ArrayOfString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArrayTestWithWrappedAndName) GetArrayOfStringOk() ([]string, bool) {
	if o == nil || IsNil(o.ArrayOfString) {
		return nil, false
	}
	return o.ArrayOfString, true
}

// HasArrayOfString returns a boolean if a field has been set.
func (o *ArrayTestWithWrappedAndName) HasArrayOfString() bool {
	if o != nil && !IsNil(o.ArrayOfString) {
		return true
	}

	return false
}

// SetArrayOfString gets a reference to the given []string and assigns it to the ArrayOfString field.
func (o *ArrayTestWithWrappedAndName) SetArrayOfString(v []string) {
	o.ArrayOfString = v
}

func (o ArrayTestWithWrappedAndName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArrayTestWithWrappedAndName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ArrayOfString) {
		toSerialize["array_of_string"] = o.ArrayOfString
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ArrayTestWithWrappedAndName) UnmarshalJSON(data []byte) (err error) {
	varArrayTestWithWrappedAndName := _ArrayTestWithWrappedAndName{}

	err = json.Unmarshal(data, &varArrayTestWithWrappedAndName)

	if err != nil {
		return err
	}

	*o = ArrayTestWithWrappedAndName(varArrayTestWithWrappedAndName)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "array_of_string")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableArrayTestWithWrappedAndName struct {
	value *ArrayTestWithWrappedAndName
	isSet bool
}

func (v NullableArrayTestWithWrappedAndName) Get() *ArrayTestWithWrappedAndName {
	return v.value
}

func (v *NullableArrayTestWithWrappedAndName) Set(val *ArrayTestWithWrappedAndName) {
	v.value = val
	v.isSet = true
}

func (v NullableArrayTestWithWrappedAndName) IsSet() bool {
	return v.isSet
}

func (v *NullableArrayTestWithWrappedAndName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArrayTestWithWrappedAndName(val *ArrayTestWithWrappedAndName) *NullableArrayTestWithWrappedAndName {
	return &NullableArrayTestWithWrappedAndName{value: val, isSet: true}
}

func (v NullableArrayTestWithWrappedAndName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArrayTestWithWrappedAndName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


