/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.apis.StuffApi
import org.openapitools.client.models.FindStuff200Response

class StuffApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StuffApi
        //val apiInstance = StuffApi()

        // to test findStuff
        should("test findStuff") {
            // uncomment below to test findStuff
            //val result : FindStuff200Response = apiInstance.findStuff()
            //result shouldBe ("TODO")
        }

    }
}
