# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UpdatePetWithFormBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, status: str=None):
        """UpdatePetWithFormBody - a model defined in OpenAPI

        :param name: The name of this UpdatePetWithFormBody.
        :param status: The status of this UpdatePetWithFormBody.
        """
        self.openapi_types = {
            'name': str,
            'status': str
        }

        self.attribute_map = {
            'name': 'name',
            'status': 'status'
        }

        self._name = name
        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UpdatePetWithFormBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The updatePetWithFormBody of this UpdatePetWithFormBody.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this UpdatePetWithFormBody.

        Updated name of the pet

        :return: The name of this UpdatePetWithFormBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UpdatePetWithFormBody.

        Updated name of the pet

        :param name: The name of this UpdatePetWithFormBody.
        :type name: str
        """

        self._name = name

    @property
    def status(self):
        """Gets the status of this UpdatePetWithFormBody.

        Updated status of the pet

        :return: The status of this UpdatePetWithFormBody.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UpdatePetWithFormBody.

        Updated status of the pet

        :param status: The status of this UpdatePetWithFormBody.
        :type status: str
        """

        self._status = status
