/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TypeHolderExample
 */
class TypeHolderExampleTest {
    private final TypeHolderExample model = new TypeHolderExample();

    /**
     * Model tests for TypeHolderExample
     */
    @Test
    void testTypeHolderExample() {
        // TODO: test TypeHolderExample
    }

    /**
     * Test the property 'stringItem'
     */
    @Test
    void stringItemTest() {
        // TODO: test stringItem
    }

    /**
     * Test the property 'numberItem'
     */
    @Test
    void numberItemTest() {
        // TODO: test numberItem
    }

    /**
     * Test the property 'floatItem'
     */
    @Test
    void floatItemTest() {
        // TODO: test floatItem
    }

    /**
     * Test the property 'integerItem'
     */
    @Test
    void integerItemTest() {
        // TODO: test integerItem
    }

    /**
     * Test the property 'boolItem'
     */
    @Test
    void boolItemTest() {
        // TODO: test boolItem
    }

    /**
     * Test the property 'arrayItem'
     */
    @Test
    void arrayItemTest() {
        // TODO: test arrayItem
    }

}
