/* tslint:disable */
/* eslint-disable */
/**
 * Enum test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NullableNumberEnum1
 */
export interface NullableNumberEnum1 {
}

export function NullableNumberEnum1FromJSON(json: any): NullableNumberEnum1 {
    return NullableNumberEnum1FromJSONTyped(json, false);
}

export function NullableNumberEnum1FromJSONTyped(json: any, ignoreDiscriminator: boolean): NullableNumberEnum1 {
    return json;
}

export function NullableNumberEnum1ToJSON(value?: NullableNumberEnum1 | null): any {
    return value;
}


