/* tslint:disable */
/* eslint-disable */
/**
 * Enum test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StringOneOf,
    StringOneOfFromJSON,
    StringOneOfFromJSONTyped,
    StringOneOfToJSON,
} from './';

/**
 * 
 * @export
 * @interface ObjectCombinedEnum
 */
export interface ObjectCombinedEnum {
    /**
     * 
     * @type {StringOneOf}
     * @memberof ObjectCombinedEnum
     */
    combinedStringEnum?: StringOneOf;
}

export function ObjectCombinedEnumFromJSON(json: any): ObjectCombinedEnum {
    return ObjectCombinedEnumFromJSONTyped(json, false);
}

export function ObjectCombinedEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectCombinedEnum {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'combinedStringEnum': !exists(json, 'combined-string-enum') ? undefined : StringOneOfFromJSON(json['combined-string-enum']),
    };
}

export function ObjectCombinedEnumToJSON(value?: ObjectCombinedEnum | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'combined-string-enum': StringOneOfToJSON(value.combinedStringEnum),
    };
}


