/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.OuterEnum;
import org.openapitools.client.model.OuterEnumDefaultValue;
import org.openapitools.client.model.OuterEnumInteger;
import org.openapitools.client.model.OuterEnumIntegerDefaultValue;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EnumTest
 */
public class EnumTestTest {
    private final EnumTest model = new EnumTest();

    /**
     * Model tests for EnumTest
     */
    @Test
    public void testEnumTest() {
        // TODO: test EnumTest
    }

    /**
     * Test the property 'enumString'
     */
    @Test
    public void enumStringTest() {
        // TODO: test enumString
    }

    /**
     * Test the property 'enumStringRequired'
     */
    @Test
    public void enumStringRequiredTest() {
        // TODO: test enumStringRequired
    }

    /**
     * Test the property 'enumInteger'
     */
    @Test
    public void enumIntegerTest() {
        // TODO: test enumInteger
    }

    /**
     * Test the property 'enumNumber'
     */
    @Test
    public void enumNumberTest() {
        // TODO: test enumNumber
    }

    /**
     * Test the property 'outerEnum'
     */
    @Test
    public void outerEnumTest() {
        // TODO: test outerEnum
    }

    /**
     * Test the property 'outerEnumInteger'
     */
    @Test
    public void outerEnumIntegerTest() {
        // TODO: test outerEnumInteger
    }

    /**
     * Test the property 'outerEnumDefaultValue'
     */
    @Test
    public void outerEnumDefaultValueTest() {
        // TODO: test outerEnumDefaultValue
    }

    /**
     * Test the property 'outerEnumIntegerDefaultValue'
     */
    @Test
    public void outerEnumIntegerDefaultValueTest() {
        // TODO: test outerEnumIntegerDefaultValue
    }

}
