/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package petstore
type EnumQueryInteger int32

// List of enum_query_integer
const (
	ENUM_QUERY_INTEGER_1 EnumQueryInteger = 1
	ENUM_QUERY_INTEGER_MINUS_2 EnumQueryInteger = -2
)