"""
    OpenAPI Petstore

    This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import petstore_api
from petstore_api.model.polygon_all_of import PolygonAllOf


class TestPolygonAllOf(unittest.TestCase):
    """PolygonAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolygonAllOf(self):
        """Test PolygonAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PolygonAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
