/*
 * Files.com API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@files.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ActionNotificationExportEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ActionNotificationExportEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ActionNotificationExportEntity
        //private ActionNotificationExportEntity instance;

        public ActionNotificationExportEntityTests()
        {
            // TODO uncomment below to create an instance of ActionNotificationExportEntity
            //instance = new ActionNotificationExportEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActionNotificationExportEntity
        /// </summary>
        [Fact]
        public void ActionNotificationExportEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" ActionNotificationExportEntity
            //Assert.IsType<ActionNotificationExportEntity>(instance);
        }

        /// <summary>
        /// Test the property 'EndAt'
        /// </summary>
        [Fact]
        public void EndAtTest()
        {
            // TODO unit test for the property 'EndAt'
        }

        /// <summary>
        /// Test the property 'ExportVersion'
        /// </summary>
        [Fact]
        public void ExportVersionTest()
        {
            // TODO unit test for the property 'ExportVersion'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'QueryFolder'
        /// </summary>
        [Fact]
        public void QueryFolderTest()
        {
            // TODO unit test for the property 'QueryFolder'
        }

        /// <summary>
        /// Test the property 'QueryMessage'
        /// </summary>
        [Fact]
        public void QueryMessageTest()
        {
            // TODO unit test for the property 'QueryMessage'
        }

        /// <summary>
        /// Test the property 'QueryPath'
        /// </summary>
        [Fact]
        public void QueryPathTest()
        {
            // TODO unit test for the property 'QueryPath'
        }

        /// <summary>
        /// Test the property 'QueryRequestMethod'
        /// </summary>
        [Fact]
        public void QueryRequestMethodTest()
        {
            // TODO unit test for the property 'QueryRequestMethod'
        }

        /// <summary>
        /// Test the property 'QueryRequestUrl'
        /// </summary>
        [Fact]
        public void QueryRequestUrlTest()
        {
            // TODO unit test for the property 'QueryRequestUrl'
        }

        /// <summary>
        /// Test the property 'QueryStatus'
        /// </summary>
        [Fact]
        public void QueryStatusTest()
        {
            // TODO unit test for the property 'QueryStatus'
        }

        /// <summary>
        /// Test the property 'QuerySuccess'
        /// </summary>
        [Fact]
        public void QuerySuccessTest()
        {
            // TODO unit test for the property 'QuerySuccess'
        }

        /// <summary>
        /// Test the property 'ResultsUrl'
        /// </summary>
        [Fact]
        public void ResultsUrlTest()
        {
            // TODO unit test for the property 'ResultsUrl'
        }

        /// <summary>
        /// Test the property 'StartAt'
        /// </summary>
        [Fact]
        public void StartAtTest()
        {
            // TODO unit test for the property 'StartAt'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
