platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'SwaggerClient' do
    pod "PetstoreClient", :path => "../"

    target 'SwaggerClientTests' do
        inherit! :search_paths
    end
end
