FROM golang:1.25.6-alpine as build-env
RUN apk add --no-cache git gcc
RUN mkdir /app
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o {{packageName}}
FROM alpine
COPY --from=build-env /app/{{packageName}} .
EXPOSE 8080/tcp
USER 1001
ENTRYPOINT ["./{{packageName}}"]
