use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'TestClientApp' do
    pod "TestClient", :path => "../"
    pod 'Alamofire', '~> 4.5'

    target 'TestClientAppTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "4.0"
        end
    end
end
