= OpenAPI Generator Gradle Plugin

This document describes the Gradle plugin for OpenAPI Generator.

This Gradle plugin offers a declarative DSL via _extensions_ (these are Gradle project extensions).
These map almost fully 1:1 with the options you'd pass to the CLI or Maven plugin. The plugin maps the extensions to a task of the same name to provide a clean API. If you're interested in the extension/task mapping concept from a high-level, you can https://docs.gradle.org/current/userguide/custom_plugins.html#sec:mapping_extension_properties_to_task_properties[check out Gradle's docs].

== Tasks

Tasks are listed under the "OpenAPI Tools" tasks heading.

.OpenAPI Tools Tasks
|===
|task name |description

|*openApiGenerate*
|Generate code via Open API Tools Generator for Open API 2.0 or 3.x specification documents.

|*openApiGenerators*
|Lists generators available via Open API Generators.

|*openApiMeta*
|Generates a new generator to be consumed via Open API Generator.

|*openApiValidate*
|Validates an Open API 2.0 or 3.x specification document.
|===


[NOTE]
====
The plugin implements the above tasks as project extensions of the same name. If you'd like to declare
these tasks as dependencies to other tasks (using `dependsOn`), you'll need  a task reference. e.g.:

```
compileJava.dependsOn tasks.openApiGenerate
```
====

All extensions can be rewritten as tasks. Where you can have only a single extension defined in your Gradle file, you may have multiple tasks.

.One Extension, multiple tasks
[source,groovy]
----
// Validating a single specification
openApiValidate {
    inputSpec.set("$rootDir/petstore-v3.0-invalid.yaml")
}

// Define a task for validating one specification
task validateGoodSpec(type: org.openapitools.generator.gradle.plugin.tasks.ValidateTask) {
    inputSpec.set("$rootDir/petstore-v3.0.yaml")
}

// Define a task for validating another specification
task validateBadSpec(type: org.openapitools.generator.gradle.plugin.tasks.ValidateTask) {
    inputSpec.set("$rootDir/petstore-v3.0-invalid.yaml")
}

// Define a task for batch validations
task validateSpecs(dependsOn: ['validateGoodSpec', 'validateBadSpec'])
----

[NOTE]
====
**Modern Gradle Support:** This plugin fully supports Gradle's **Configuration Cache**, **Build Cache**, and **Lazy Configuration (Provider API)**.

Enable caching globally by setting `org.gradle.caching=true` and `org.gradle.configuration-cache=true` in your `gradle.properties` file, or by passing `--build-cache` and `--configuration-cache` on the command line.

If you need to disable up-to-date checks and caching for a specific task, you can do so like this:

.Disable caching for extension
[source,groovy]
----
tasks.withType(org.openapitools.generator.gradle.plugin.tasks.GenerateTask).configureEach {
    outputs.upToDateWhen { false }
    outputs.cacheIf { false }
}
----
Disable up-to-date checks and caching for a custom task:

.Disable caching for custom task
[source,groovy]
----
task validateGoodSpec(type: org.openapitools.generator.gradle.plugin.tasks.ValidateTask) {
    outputs.upToDateWhen { false }
    outputs.cacheIf { false }

    inputSpec.set("$rootDir/petstore-v3.0.yaml")
}
----
====

== Plugin Setup

//# RELEASE_VERSION

[source,group]
----
plugins {
  id "org.openapi.generator" version "7.22.0"
}
----

Using https://docs.gradle.org/current/userguide/plugins.html#sec:old_plugin_application[legacy plugin application]:

[source,groovy]
----
buildscript {
  repositories {
    mavenLocal()
    mavenCentral()
    // or, via Gradle Plugin Portal:
    // url "https://plugins.gradle.org/m2/"
  }
  dependencies {
    classpath "org.openapitools:openapi-generator-gradle-plugin:7.19.0"
  }
}

apply plugin: 'org.openapi.generator'
----
//# /RELEASE_VERSION

== Configuration

=== openApiGenerate

.Options
|===
|Key |Data Type |Default |Description

|verbose
|Boolean / Provider<Boolean>
|false
|The verbosity of generation

|validateSpec
|Boolean / Provider<Boolean>
|true
|Whether or not we should validate the input spec before generation. Invalid specs result in an error.

|generatorName
|String / Provider<String>
|None
|The name of the generator which will handle codegen.

|outputDir
|String / Provider<Directory>
|None
|The output target directory into which code will be generated.

|inputSpec
|String / Provider<RegularFile>
|None
|The Open API 2.0/3.x specification location. This acts as a smart router: if a local path is provided, it utilizes Gradle's Lazy File API for caching. If a URL/URI (e.g., `http://`, `jar:`) is provided, it automatically routes to `remoteInputSpec`.

|inputSpecRootDirectory
|String / Provider<Directory>
|None
|Local root folder with spec file(s)

|mergedFileName
|String / Provider<String>
|None
|Name of the file that will contain all merged specs

|remoteInputSpec
|String / Provider<String>
|None
|The remote Open API 2.0/3.x specification URL location. (Note: Using remote specs may result in stale build caches if the remote content changes without the URL changing).

|templateDir
|String / Provider<Directory>
|None
|The template directory holding a custom template.

|templateResourcePath
|String / Provider<String>
|None
|Directory with mustache templates via resource path. This option will overwrite any option defined in `templateDir`

|auth
|String / Provider<String>
|None
|Adds authorization headers when fetching the OpenAPI definitions remotely. Pass in a URL-encoded string of name:header with a comma separating multiple values.

|globalProperties
|Map / Provider<Map>
|None
|Sets specified global properties.

|configFile
|String / Provider<RegularFile>
|None
|Path to json configuration file. See OpenAPI Generator readme for structure details.

|skipOverwrite
|Boolean / Provider<Boolean>
|false
|Specifies if the existing files should be overwritten during the generation.

|packageName
|String / Provider<String>
|(generator specific)
|Package for generated classes (where supported).

|apiPackage
|String / Provider<String>
|(generator specific)
|Package for generated api classes.

|modelPackage
|String / Provider<String>
|(generator specific)
|Package for generated model classes.

|modelNamePrefix
|String / Provider<String>
|None
|Prefix that will be prepended to all model names.

|modelNameSuffix
|String / Provider<String>
|None
|Suffix that will be appended to all model names.

|apiNameSuffix
|String / Provider<String>
|None
|Suffix that will be appended to all api names.

|instantiationTypes
|Map / Provider<Map>
|None
|Sets instantiation type mappings.

|typeMappings
|Map / Provider<Map>
|None
|Sets mappings between OpenAPI spec types and generated code types in the format of OpenAPIType=generatedType,OpenAPIType=generatedType. For example: `array=List,map=Map,string=String`. You can also have multiple occurrences of this option. To map a specified format, use type+format, e.g. string+password=EncryptedString will map `type: string, format: password` to `EncryptedString`.

|schemaMappings
|Map / Provider<Map>
|None
|specifies mappings between the schema and the new name in the format of schema_a=Cat,schema_b=Bird. https://openapi-generator.tech/docs/customization/#schema-mapping

|nameMappings
|Map / Provider<Map>
|None
|specifies mappings between the property name and the new name in the format of property_a=firstProperty,property_b=secondProperty. https://openapi-generator.tech/docs/customization/#name-mapping

|modelNameMappings
|Map / Provider<Map>
|None
|specifies mappings between the model name and the new name in the format of model_a=FirstModel,property_b=SecondModel. https://openapi-generator.tech/docs/customization/#name-mapping

|parameterNameMappings
|Map / Provider<Map>
|None
|specifies mappings between the parameter name and the new name in the format of parameter_a=firstParameter,parameter_b=secondParameter. https://openapi-generator.tech/docs/customization/#name-mapping

|inlineSchemaNameMappings
|Map / Provider<Map>
|None
|specifies mappings between the inline schema name and the new name in the format of inline_object_2=Cat,inline_object_5=Bird.

|inlineSchemaOptions
|Map / Provider<Map>
|None
|specifies the options used when handling inline schema in inline model resolver

|additionalProperties
|Map / Provider<Map>
|None
|Sets additional properties that can be referenced by the mustache templates.

|serverVariables
|Map / Provider<Map>
|None
|Sets server variable for server URL template substitution, in the format of name=value,name=value. You can also have multiple occurrences of this option.

|languageSpecificPrimitives
|List / Provider<List>
|None
|Specifies additional language specific primitive types in the format of type1,type2,type3,type3. For example: String,boolean,Boolean,Double.

|importMappings
|Map / Provider<Map>
|None
|Specifies mappings between a given class and the import that should be used for that class.

|invokerPackage
|String / Provider<String>
|None
|Root package for generated code.

|groupId
|String / Provider<String>
|None
|GroupId in generated pom.xml/build.gradle or other build script. Language-specific conversions occur in non-jvm generators.

|id
|String / Provider<String>
|None
|ArtifactId in generated pom.xml/build.gradle or other build script. Language-specific conversions occur in non-jvm generators.

|version
|String / Provider<String>
|None
|Artifact version in generated pom.xml/build.gradle or other build script. Language-specific conversions occur in non-jvm generators.

|library
|String / Provider<String>
|None
|Reference the library template (sub-template) of a generator.

|gitHost
|String / Provider<String>
|github.com
|Git user ID, e.g. gitlab.com.

|gitUserId
|String / Provider<String>
|None
|Git user ID, e.g. openapitools.

|gitRepoId
|String / Provider<String>
|None
|Git repo ID, e.g. openapi-generator.

|releaseNote
|String / Provider<String>
|'Minor update'
|Release note.

|httpUserAgent
|String / Provider<String>
|None
|HTTP user agent, e.g. codegen_csharp_api_client. Generator default is 'OpenAPI-Generator/{packageVersion}/{language}', but may be generator-specific.

|reservedWordsMappings
|Map / Provider<Map>
|None
|Specifies how a reserved name should be escaped to. Otherwise, the default _<name> is used.

|ignoreFileOverride
|String / Provider<RegularFile>
|None
|Specifies an override location for the .openapi-generator-ignore file. Most useful on initial generation.

|removeOperationIdPrefix
|Boolean / Provider<Boolean>
|false
|Remove prefix of operationId, e.g. config_getId => getId.

|skipOperationExample
|Boolean / Provider<Boolean>
|false
|Skip examples defined in the operation

|apiFilesConstrainedTo
|List / Provider<List>
|None
|Defines which API-related files should be generated. This allows you to create a subset of generated files (or none at all). See Note Below.

|modelFilesConstrainedTo
|List / Provider<List>
|None
|Defines which model-related files should be generated. This allows you to create a subset of generated files (or none at all). See Note Below.

|supportingFilesConstrainedTo
|List / Provider<List>
|None
|Defines which supporting files should be generated. This allows you to create a subset of generated files (or none at all). See Note Below.

|generateModelTests
|Boolean / Provider<Boolean>
|true
|Defines whether or not model-related _test_ files should be generated.

|generateModelDocumentation
|Boolean / Provider<Boolean>
|true
|Defines whether or not model-related _documentation_ files should be generated.

|generateApiTests
|Boolean / Provider<Boolean>
|true
|Defines whether or not api-related _test_ files should be generated.

|generateApiDocumentation
|Boolean / Provider<Boolean>
|true
|Defines whether or not api-related _documentation_ files should be generated.

|configOptions
|Map / Provider<Map>
|None
|A map of options specific to a generator. To see the full list of generator-specified parameters, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators.md[generators docs]. Note that any config options from a generator specific document may go here, and some generators may duplicate other options which are siblings to `configOptions`.

|logToStderr
|Boolean / Provider<Boolean>
|false
|To write all log messages (not just errors) to STDOUT

|enablePostProcessFile
|Boolean / Provider<Boolean>
|false
|To enable the file post-processing hook. This enables executing an external post-processor (usually a linter program). This only enables the post-processor. To define the post-processing command, define an environment variable such as LANG_POST_PROCESS_FILE (e.g. GO_POST_PROCESS_FILE, SCALA_POST_PROCESS_FILE). Please open an issue if your target generator does not support this functionality.

|skipValidateSpec
|Boolean / Provider<Boolean>
|false
|To skip spec validation. When true, we will skip the default behavior of validating a spec before generation.

|openapiNormalizer
|Map / Provider<Map>
|None
|specifies the rules to be enabled in OpenAPI normalizer in the form of RULE_1=true,RULE_2=original.

|generateAliasAsModel
|Boolean / Provider<Boolean>
|false
|To generate alias (array, list, map) as model. When false, top-level objects defined as array, list, or map will result in those definitions generated as top-level Array-of-items, List-of-items, Map-of-items definitions. When true, A model representation either containing or extending the array,list,map (depending on specific generator implementation) will be generated.

|engine
|String / Provider<String>
|mustache
|Templating engine: "mustache" (default) or "handlebars" (beta)

|cleanupOutput
|Boolean / Provider<Boolean>
|false
|Defines whether the output directory should be cleaned up before generating the output.

|dryRun
|Boolean / Provider<Boolean>
|false
|Defines whether the generator should run in dry-run mode. In dry-run mode no files are written and a summary about
file states is output.
|===

[NOTE]
====
Configuring any one of `apiFilesConstrainedTo`, `modelFilesConstrainedTo`, or `supportingFilesConstrainedTo` results
in others being disabled. That is, OpenAPI Generator considers any one of these to define a subset of generation.

For more control over generation of individual files, configure an ignore file and refer to it via `ignoreFileOverride`.
====

[NOTE]
====
When configuring `globalProperties` in order to perform selective generation you can disable generation of some parts by providing `"false"` value:
[source,groovy]
----
openApiGenerate {
// other settings omitted
globalProperties.set([
modelDocs: "false",
apis: "false"
])
}
----
When enabling generation of only specific parts you either have to provide CSV list of what you particularly are generating or provide an empty string `""` to generate everything. If you provide `"true"` it will be treated as a specific name of model or api you want to generate.
[source,groovy]
----
openApiGenerate {
// other settings omitted
globalProperties.set([
apis: "",
models: "User:Pet"
])
}
----
====

=== openApiValidate

.Options
|===
|Key |Data Type |Default |Description

|inputSpec
|String / Provider<RegularFile>
|None
|The input specification to validate. Acts as a smart router, supporting local files (with full Gradle caching) or remote URLs/URIs.

|recommend
|Boolean
|true
|Whether or not to offer recommendations related to the validated specification document.

|===

=== openApiMeta

.Options
|===
|Key |Data Type |Default |Description

|generatorName
|String
|None
|The human-readable generator name of the newly created template generator.

|packageName
|String
|org.openapitools.codegen
|The packageName generatorName to put the main class into.

|outputFolder
|String
|Current Directory
|Where to write the generated files

|===

=== openApiGenerators

.Options
|===
|Key |Data Type |Default |Description

|include
|String[]
|None
|A list of stability indexes to include (values: all,beta,stable,experimental,deprecated). Excludes deprecated by default.

|===

== Examples

=== openApiGenerate

This task exposes all options available via OpenAPI Generator CLI and the OpenAPI Generator Maven Plugin.

.in build.gradle
[source,groovy]
----
openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set("$rootDir/specs/petstore-v3.0.yaml")
    outputDir.set(layout.buildDirectory.dir("generated").get().asFile.path)
    apiPackage.set("org.openapi.example.api")
    invokerPackage.set("org.openapi.example.invoker")
    modelPackage.set("org.openapi.example.model")
    configOptions.put("dateLibrary", "java8")
}
----

The above code demonstrates configuration of global options as well as generator-specific config options.

=== openApiGenerators

This is an output-only listing task. There's no need to add configuration to build.gradle.

.Example output of openApiGenerators task
[source,terminal]
----
$ ./gradlew openApiGenerators

> Task :openApiGenerators
The following generators are available:

CLIENT generators:
    - ada
…

SERVER generators:
    - ada-server
…

DOCUMENTATION generators:
    - cwiki
…

CONFIG generators:
    - apache2

OTHER generators:
…

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
----

[NOTE]
====
Generator type listings in the above example have been truncated to avoid potential confusion with changing generator support.

Please run the above task to list all available generators.
====

=== openApiMeta

.in build.gradle
[source,groovy]
----
openApiMeta {
   generatorName.set("Jim")
   packageName.set("us.jimschubert.example")
}
----

.Example output of openApiMeta task
[source,terminal]
----
$ ./gradlew openApiMeta

> Task :openApiMeta
Wrote file to /Users/jim/my_project/pom.xml
Wrote file to /Users/jim/my_project/src/main/java/us/jimschubert/example/JimGenerator.java
Wrote file to /Users/jim/my_project/README.md
Wrote file to /Users/jim/my_project/src/main/resources/jim/api.mustache
Wrote file to /Users/jim/my_project/src/main/resources/jim/model.mustache
Wrote file to /Users/jim/my_project/src/main/resources/jim/myFile.mustache
Wrote file to /Users/jim/my_project/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig
Created generator JimGenerator

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
----


=== openApiValidate

.in build.gradle
[source,groovy]
----
openApiValidate {
   inputSpec.set("/src/openapi-generator/modules/openapi-generator/src/test/resources/3_0/petstore.yaml")
   recommend.set(true)
}
----

.Example output of openApiValidate task (success)
[source,terminal]
----
$ ./gradlew openApiValidate --input=/Users/jim/projects/openapi-generator/modules/openapi-generator/src/test/resources/3_0/ping.yaml

> Task :openApiValidate
Validating spec /Users/jim/projects/openapi-generator/modules/openapi-generator/src/test/resources/3_0/ping.yaml
Spec is valid.

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
----

.Example output of openApiValidate task (failure)
[source,terminal]
----
$ ./gradlew openApiValidate

> Task :openApiValidate FAILED
Validating spec /Users/jim/projects/openapi-generator/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

Spec is invalid.
Issues:

        attribute info is missing


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':openApiValidate'.
> Validation failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

----

.in terminal (alternate)
[source,terminal]
----
$ ./gradlew openApiValidate --input=/Users/jim/projects/openapi-generator/modules/openapi-generator/src/test/resources/3_0/petstore.yaml
----

=== Groovy DSL Bridge Methods

Both project extensions and custom task instances provide bridge methods that allow Groovy DSL users to set file and directory properties using simple String paths. These bridge methods support both **method-style** and **property-style** syntax.

==== Extension Bridge Methods (for openApiGenerate, openApiValidate, openApiMeta)

When configuring project extensions like `openApiGenerate { }`, `openApiValidate { }`, or `openApiMeta { }`, Groovy DSL users can use bridge methods to set properties with String paths.

.Available Extension Bridge Methods
|===
|Extension |Available Methods

|`openApiGenerate`
|`setInputSpec(path)`, `setOutputDir(path)`, `setTemplateDir(path)`, `setConfigFile(path)`, `setIgnoreFileOverride(path)`, `setInputSpecRootDirectory(path)`

|`openApiValidate`
|`setInputSpec(path)`

|`openApiMeta`
|`setOutputFolder(path)`
|===

.Example: Using extension bridge methods in Groovy DSL
[source,groovy]
----
// Method-style syntax
openApiGenerate {
    generatorName.set("kotlin")
    setInputSpec("$rootDir/specs/petstore.yaml")
    setOutputDir("build/generated")
    apiPackage.set("org.openapi.example.api")
}

// Property-style syntax (Groovy allows this syntactic sugar)
openApiGenerate {
    generatorName.set("kotlin")
    inputSpec = "$rootDir/specs/petstore.yaml"
    outputDir = "build/generated"
    apiPackage.set("org.openapi.example.api")
}

// Also works with openApiValidate
openApiValidate {
    inputSpec = "$rootDir/specs/petstore.yaml"
    recommend.set(true)
}

// And openApiMeta
openApiMeta {
    generatorName.set("MyGenerator")
    outputFolder = "build/custom-generator"
}
----

[IMPORTANT]
====
**Smart Input Routing:** The `setInputSpec()` method for extensions (and `setInputSpecAsString()` for custom tasks) automatically detects whether the provided path is a remote URL (e.g., `http://`, `https://`, `jar:`) or a local file path, and routes it to the appropriate property (`remoteInputSpec` or `inputSpec`).

Additionally, when you set a local file path after previously setting a remote URL (or vice versa), the method automatically clears the conflicting property to prevent stale values from taking precedence. This ensures your configuration behaves predictably even when you change between local and remote specs.
====

=== Generate multiple sources

If you want to perform multiple generation tasks, you'd want to create a task that inherits from the `GenerateTask`.
Examples can be found in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/samples/local-spec/build.gradle[samples/local-spec/build.gradle].

You can define any number of generator tasks; the generated code does _not_ need to be a JVM language.

```gradle
task buildGoClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName.set("go")
    inputSpec.set("$rootDir/petstore-v3.0.yaml")
    additionalProperties.set([
            packageName: "petstore"
    ])
    outputDir.set(layout.buildDirectory.dir("go").get().asFile.path)
    configOptions.set([
            dateLibrary: "threetenp"
    ])
}
task buildKotlinClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName.set("kotlin")
    inputSpec.set("$rootDir/petstore-v3.0.yaml")
    outputDir.set(layout.buildDirectory.dir("kotlin").get().asFile.path)
    apiPackage.set("org.openapitools.example.api")
    invokerPackage.set("org.openapitools.example.invoker")
    modelPackage.set("org.openapitools.example.model")
    configOptions.set([
            dateLibrary: "java8"
    ])
    globalProperties.set([
            modelDocs: "false"
    ])
}
```

==== Custom Task Bridge Methods (AsString suffix)

When creating custom task instances (as shown above), Groovy DSL users also have access to bridge methods with the `AsString` suffix. These methods provide the same functionality as the extension bridge methods.

[NOTE]
====
**Why the "AsString" suffix?**

Due to technical limitations with Gradle's abstract property getters in task classes, the bridge methods for custom tasks require the `AsString` suffix to avoid naming conflicts with Gradle's internal getter methods.

- **Extensions** (e.g., `openApiGenerate { }`) use methods like `setInputSpec()`, `setOutputDir()`
- **Custom Tasks** (e.g., `task myTask(type: GenerateTask) { }`) use methods like `setInputSpecAsString()`, `setOutputDirAsString()`

Both patterns work identically for String-based property configuration in Groovy DSL.
====

.Available AsString Bridge Methods for Custom Tasks
|===
|Task Type |Available Methods

|`GenerateTask`
|`setInputSpecAsString(path)`, `setOutputDirAsString(path)`, `setTemplateDirAsString(path)`, `setConfigFileAsString(path)`, `setIgnoreFileOverrideAsString(path)`, `setInputSpecRootDirectoryAsString(path)`, `setSchemaLocationAsString(path)`

|`ValidateTask`
|`setInputSpecAsString(path)`

|`MetaTask`
|`setOutputFolderAsString(path)`
|===

.Example: Using AsString methods in Groovy DSL
[source,groovy]
----
// Method-style syntax
task buildCustomClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName.set("kotlin")
    setInputSpecAsString("$rootDir/specs/api.yaml")
    setOutputDirAsString("build/generated/custom")
    setTemplateDirAsString("templates/custom")
    apiPackage.set("com.example.api")
}

// Property-style syntax (Groovy allows this syntactic sugar)
task buildAnotherClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName.set("java")
    inputSpecAsString = "$rootDir/specs/another-api.yaml"
    outputDirAsString = "build/generated/another"
    modelPackage.set("com.example.model")
}
----

To execute your specs, you'd then do:

```
./gradlew buildGoClient buildKotlinClient
```

If you want to simplify the execution, you could create a new task with `dependsOn`.

```gradle
task codegen(dependsOn: ['buildGoClient', 'buildKotlinClient'])
```

Or, if you're generating the code on compile, you can add these as a dependency to `compileJava` or any other existing task.
You can also mix the default task `openApiGenerate` with custom tasks:

```gradle
compileJava.dependsOn buildKotlinClient, tasks.openApiGenerate
```

[NOTE]
====
`openApiGenerate` is a project extension _and_ a task. If you want to use this in `dependsOn`,
you need a task reference or instance. One way to do this is to access it as `tasks.openApiGenerate`.

You can run `gradle tasks --debug` to see this registration.
====

=== Advanced: Task Wiring and Lazy Configuration

The OpenAPI Generator plugin fully supports Gradle's Provider API and Lazy Configuration. This means that if your OpenAPI spec is generated or downloaded by another Gradle task, you **do not** need to use `dependsOn` or hardcode paths in the `buildDir`.

Instead of passing a static string path, simply pass the output `Provider` from your producer task directly into the generator's properties. Gradle will automatically build the task dependency graph and execute them in the correct order.

.Implicit Task Wiring (Kotlin DSL)
[source,kotlin]
----
// 1. A task that produces a spec file
val downloadSpec by tasks.registering(DownloadTask::class) {
    sourceUrl.set("https://api.mycompany.com/openapi.yaml")
    outputFile.set(layout.buildDirectory.file("downloaded-spec.yaml"))
}

// 2. The generator task
openApiGenerate {
    generatorName.set("kotlin")

    // Wire the output of the download task directly to the input of the generator.
    // Gradle automatically knows `openApiGenerate` depends on `downloadSpec`.
    inputSpec.set(downloadSpec.flatMap { it.outputFile })

    outputDir.set(layout.buildDirectory.dir("generated-code"))
}
----

[NOTE]
====
**Provider API vs Bridge Methods:**

For optimal lazy configuration and task wiring, both Groovy and Kotlin DSL users should use `.set()` with the Provider API when possible (e.g., `inputSpec.set(downloadSpec.flatMap { it.outputFile })`).

For simpler cases with static String paths, Groovy DSL users can use the convenient bridge methods:
- Extension configuration: Use methods like `setInputSpec()`, `setOutputDir()` (see "Extension Bridge Methods" section)
- Custom task configuration: Use methods like `setInputSpecAsString()`, `setOutputDirAsString()` (see "Custom Task Bridge Methods" section)
====

== Troubleshooting

=== Android Studio

Android Studio may experience a Windows-specific Guava dependency conflict with openapi-generator-gradle-plugin versions greater than 3.0.0.

As a workaround, you may force exclude conflicting Guava dependencies.

//# RELEASE_VERSION
```gradle
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath('org.openapitools:openapi-generator-gradle-plugin:7.19.0') {
            exclude group: 'com.google.guava'
        }
    }
}
// …

configurations {
    compile.exclude module: 'guava-jdk5'
}
// …
apply plugin: 'org.openapi.generator'
```
//# /RELEASE_VERSION

See https://github.com/OpenAPITools/openapi-generator/issues/1818[OpenAPITools/openapi-generator#1818] for more details.
