use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'SwaggerClient' do
    pod "PetstoreClient", :path => "../"

    target 'SwaggerClientTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
