/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Query
 * @param outcomes 
 */


data class ApiQuery (

    /* Query */
    @Json(name = "id")
    val id: kotlin.Long? = null,

    @Json(name = "outcomes")
    val outcomes: kotlin.collections.List<ApiQuery.Outcomes>? = null

) {

    /**
     * 
     *
     * Values: SUCCESS,FAILURE,SKIPPED
     */
    @JsonClass(generateAdapter = false)
    enum class Outcomes(val value: kotlin.String) {
        @Json(name = "SUCCESS") SUCCESS("SUCCESS"),
        @Json(name = "FAILURE") FAILURE("FAILURE"),
        @Json(name = "SKIPPED") SKIPPED("SKIPPED");
    }

}

