# #OpenAPI Petstore
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.24.0-SNAPSHOT
#

module Petstore
  class User
    include JSON::Serializable
    include YAML::Serializable
    include Petstore::Serializable
    include Petstore::Validation

    # Optional properties
    @[JSON::Field(key: "id", emit_null: false)]
    property id : Int64?

    @[JSON::Field(key: "username", emit_null: false)]
    property username : String?

    @[JSON::Field(key: "firstName", emit_null: false)]
    property first_name : String?

    @[JSON::Field(key: "lastName", emit_null: false)]
    property last_name : String?

    @[JSON::Field(key: "email", emit_null: false)]
    property email : String?

    @[JSON::Field(key: "password", emit_null: false)]
    property password : String?

    @[JSON::Field(key: "phone", emit_null: false)]
    property phone : String?

    # User Status
    @[JSON::Field(key: "userStatus", emit_null: false)]
    property user_status : Int32?


    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@id : Int64? = nil, @username : String? = nil, @first_name : String? = nil, @last_name : String? = nil, @email : String? = nil, @password : String? = nil, @phone : String? = nil, @user_status : Int32? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(id, username, first_name, last_name, email, password, phone, user_status)
  end

end
