//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openapi/api.dart';
import 'package:test/test.dart';

// these tests are not regenerated by dart 2 generator as they break compatibility with Dart versions under 2.12
// tests for Animal
void main() {
  // final instance = Animal();

  group('test Animal', () {
    // String className
    test('to test the property `className`', () async {
      // TODO
    });

    // String color (default value: 'red')
    test('to test the property `color`', () async {
      // TODO
    });


  });

}
