version=3.10.6
runner.dialect = scala213
project {
  git = false
  excludeFilters = [
    scalafmt-benchmarks/src/resources,
    sbt-test
    bin/issue
  ]
  layout = StandardConvention
}
align {
  preset = none
  stripMargin = true
}
binPack {
  importSelectors = fold
}
newlines {
  avoidForSimpleOverflow = all
  ignoreInSyntax = false
  source = fold
}
rewrite {
  rules = [
    AvoidInfix,
    Imports,
    RedundantBraces,
    RedundantParens,
    SortModifiers,
  ]
  imports {
    selectors = fold
    removeRedundantSelectors = true
    sort = ascii
    groups = [
      ["org\\.scalafmt\\..*"],
      ["scala\\.meta\\..*", "org\\.scalameta\\..*"],
      ["sbt\\..*"],
      ["java.?\\..*"],
      ["scala\\..*"],
      ["org\\..*"],
      ["com\\..*"],
    ]
  }
  redundantBraces {
    preset = all
    oneStatApply {
      parensMaxSpan = 300
      bracesMinSpan = 300
    }
  }
  redundantParens {
    preset = all
  }
  sortModifiers.preset = styleGuide
  trailingCommas.style = "always"
}
