# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from edu_sharing_client_api.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    NoneClass,
    BoolClass,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class Usage(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'appUser',
        'appUserMail',
        'courseId',
        'appId',
        'nodeId',
        'parentNodeId',
        'usageVersion',
        'resourceId',
    ))
    fromUsed = DateTimeSchema
    toUsed = DateTimeSchema
    usageCounter = Int32Schema
    appSubtype = StrSchema
    appType = StrSchema
    _items = StrSchema
    created = DateTimeSchema
    modified = DateTimeSchema
    appUser = StrSchema
    appUserMail = StrSchema
    courseId = StrSchema
    distinctPersons = Int32Schema
    appId = StrSchema
    nodeId = StrSchema
    parentNodeId = StrSchema
    usageVersion = StrSchema

    @classmethod
    @property
    def usageXmlParams(cls) -> typing.Type['Parameters']:
        return Parameters
    usageXmlParamsRaw = StrSchema
    resourceId = StrSchema
    guid = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        appUser: appUser,
        appUserMail: appUserMail,
        courseId: courseId,
        appId: appId,
        nodeId: nodeId,
        parentNodeId: parentNodeId,
        usageVersion: usageVersion,
        resourceId: resourceId,
        fromUsed: typing.Union[fromUsed, Unset] = unset,
        toUsed: typing.Union[toUsed, Unset] = unset,
        usageCounter: typing.Union[usageCounter, Unset] = unset,
        appSubtype: typing.Union[appSubtype, Unset] = unset,
        appType: typing.Union[appType, Unset] = unset,
        _items: typing.Union[_items, Unset] = unset,
        created: typing.Union[created, Unset] = unset,
        modified: typing.Union[modified, Unset] = unset,
        distinctPersons: typing.Union[distinctPersons, Unset] = unset,
        usageXmlParams: typing.Union['Parameters', Unset] = unset,
        usageXmlParamsRaw: typing.Union[usageXmlParamsRaw, Unset] = unset,
        guid: typing.Union[guid, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'Usage':
        return super().__new__(
            cls,
            *args,
            appUser=appUser,
            appUserMail=appUserMail,
            courseId=courseId,
            appId=appId,
            nodeId=nodeId,
            parentNodeId=parentNodeId,
            usageVersion=usageVersion,
            resourceId=resourceId,
            fromUsed=fromUsed,
            toUsed=toUsed,
            usageCounter=usageCounter,
            appSubtype=appSubtype,
            appType=appType,
            _items=_items,
            created=created,
            modified=modified,
            distinctPersons=distinctPersons,
            usageXmlParams=usageXmlParams,
            usageXmlParamsRaw=usageXmlParamsRaw,
            guid=guid,
            _configuration=_configuration,
            **kwargs,
        )

from edu_sharing_client_api.model.parameters import Parameters
