generatorName: java
outputDir: samples/client/petstore/java/microprofile-rest-client-3.0-jackson-ignore-case
library: microprofile
inputSpec: modules/openapi-generator/src/test/resources/3_0/enum.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  serializationLibrary: jackson
  useEnumCaseInsensitive: true
  artifactId: microprofile-rest-client-3-jackson
  configKey: petstore
  microprofileRestClientVersion: "3.0"
  hideGenerationTimestamp: true
  useReflectionEqualsHashCode: true
