generatorName: java
outputDir: samples/client/petstore/java/okhttp-awsv4signature
library: okhttp
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: okhttp-awsv4signature
  hideGenerationTimestamp: "true"
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
  withAWSV4Signature: true
