generatorName: java
outputDir: samples/client/petstore/java/okhttp-nullable-required
library: okhttp
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-nullable-required.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: nullable-required-okhttp
  hideGenerationTimestamp: "true"
  useOneOfDiscriminatorLookup: "true"
  disallowAdditionalPropertiesIfNotPresent: false
