generatorName: java
outputDir: samples/client/wildcard-accept-header/java
library: okhttp-gson
inputSpec: modules/openapi-generator/src/test/resources/3_0/wildcard-accept-header.yaml
templateDir: modules/openapi-generator/src/main/resources/Java
additionalProperties:
  artifactId: wildcard-accept-header
  hideGenerationTimestamp: "true"