generatorName: jaxrs-spec
outputDir: samples/server/petstore/jaxrs-spec-interface
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS/spec
additionalProperties:
  artifactId: jaxrs-spec-interface-petstore-server
  interfaceOnly: "true"
  serializableModel: "true"
  hideGenerationTimestamp: "true"
  implicitHeadersRegex: (api_key|enum_header_string)
