generatorName: kotlin
outputDir: samples/client/petstore/kotlin-jackson3
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  serializationLibrary: jackson
  useJackson3: "true"
  artifactId: kotlin-petstore-jackson3
  enumPropertyNaming: UPPERCASE
  enumUnknownDefaultCase: "true"
