generatorName: kotlin-server
outputDir: samples/server/petstore/kotlin-server/ktor2-usetags-false
library: ktor2
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/petstore-with-tags.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-server
additionalProperties:
  hideGenerationTimestamp: "true"
  serializableModel: "true"
  useTags: "false"
