generatorName: kotlin-spring
outputDir: samples/server/petstore/kotlin-springboot-4
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  serviceImplementation: "true"
  serializableModel: "true"
  useBeanValidation: "true"
  useSpringBoot4: "true"
  useJackson3: "true"
  requestMappingMode: api_interface
  gradleBuildFile: "true"