generatorName: kotlin
outputDir: samples/client/petstore/kotlin-array-nullable-items-multiplatform
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/kotlin-array-nullable-items.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-array-nullable-items-multiplatform
  library: multiplatform
  dateLibrary: kotlinx-datetime
