generatorName: kotlin
outputDir: samples/client/petstore/kotlin-allOf-special-discriminator-kotlinx-serialization
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/polymorphism-special-discriminator.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-client
additionalProperties:
  artifactId: kotlin-allOf-special-discriminator
  serializableModel: "false"
  dateLibrary: java8
  enumUnknownDefaultCase: true
  serializationLibrary: kotlinx_serialization
