generatorName: kotlin-spring
outputDir: samples/server/others/kotlin-springboot/oneOf-discriminator
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/kotlin/polymorphism-oneof-discriminator.yaml
templateDir: modules/openapi-generator/src/main/resources/kotlin-spring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  interfaceOnly: "true"
  useSpringBoot3: "true"
