generatorName: ruby-nextgen
outputDir: samples/client/petstore/ruby-nextgen
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/ruby-nextgen
globalProperties:
  apiTests: "true"
  modelTests: "true"
  apiDocs: "false"
  modelDocs: "false"
additionalProperties:
  gemName: petstore
  moduleName: Petstore
  gemVersion: 1.0.0
