generatorName: spring
outputDir: samples/server/others/springboot-pre-authorize
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/spring/preauthorize-scopes.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  useSpringSecurityPreAuthorize: "true"
  hideGenerationTimestamp: "true"
