generatorName: spring
outputDir: samples/server/petstore/springboot-paged-model
library: spring-boot
inputSpec: modules/openapi-generator/src/test/resources/3_0/spring/petstore-paged-model.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaSpring
additionalProperties:
  documentationProvider: none
  annotationLibrary: none
  useSwaggerUI: "false"
  serializableModel: "true"
  useBeanValidation: "true"
  interfaceOnly: "true"
  skipDefaultInterface: "true"
  useSpringBoot3: "true"
  hideGenerationTimestamp: "true"
  substituteGenericPagedModel: "true"
  useTags: "true"
  requestMappingMode: api_interface
