generatorName: typescript-fetch
outputDir: samples/client/petstore/typescript-fetch/builds/model-suffix
inputSpec: modules/openapi-generator/src/test/resources/3_0/typescript-fetch/oneOf.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript-fetch
additionalProperties:
  modelSuffix: Resource
  npmName: '@openapitools/typescript-fetch-model-suffix'
  npmVersion: 1.0.0
  snapshot: false