generatorName: typescript-express-zod-client
outputDir: samples/client/petstore/typescript-express-zod-client/builds/default
inputSpec: modules/openapi-generator/src/test/resources/3_0/typescript-express-zod.yaml
additionalProperties:
  hideGenerationTimestamp: "true"
