/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param propertySize 
 * @param color 
 */


data class ApiBird (

    @SerializedName("size")
    val propertySize: String? = null,

    @SerializedName("color")
    val color: String? = null

) {


}

