# coding: utf-8

"""
    openapi 3.0.3 sample spec

    sample spec for testing openapi functionality, built from json schema tests for draft6  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import unit_test_api
from unit_test_api.model.enums_in_properties import EnumsInProperties


class TestEnumsInProperties(unittest.TestCase):
    """EnumsInProperties unit test stubs"""

    def test_missing_optional_property_is_valid_passes(self):
        # missing optional property is valid
        EnumsInProperties(
            **{
                "bar":
                    
                    "bar",
            }
        )

    def test_wrong_foo_value_fails(self):
        # wrong foo value
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError, TypeError)):
            EnumsInProperties(
                **{
                    "foo":
                        
                        "foot",
                    "bar":
                        
                        "bar",
                }
            )

    def test_both_properties_are_valid_passes(self):
        # both properties are valid
        EnumsInProperties(
            **{
                "foo":
                    
                    "foo",
                "bar":
                    
                    "bar",
            }
        )

    def test_wrong_bar_value_fails(self):
        # wrong bar value
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError, TypeError)):
            EnumsInProperties(
                **{
                    "foo":
                        
                        "foo",
                    "bar":
                        
                        "bart",
                }
            )

    def test_missing_all_properties_is_invalid_fails(self):
        # missing all properties is invalid
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError, TypeError)):
            EnumsInProperties(
                {
                }
            )

    def test_missing_required_property_is_invalid_fails(self):
        # missing required property is invalid
        with self.assertRaises((unit_test_api.ApiValueError, unit_test_api.ApiTypeError, TypeError)):
            EnumsInProperties(
                **{
                    "foo":
                        
                        "foo",
                }
            )


if __name__ == '__main__':
    unittest.main()
