requires 'Class::Accessor';
requires 'DateTime';
requires 'JSON', '>= 2.00, < 2.80';
requires 'LWP::UserAgent';
requires 'Log::Any';
requires 'Module::Find';
requires 'Module::Runtime';
requires 'Moose::Role';
requires 'URI::Query';

on 'test' => sub {
  requires 'Test::Exception';
  requires 'Test::More';
};
