//
// SampleSubClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** This is a subclass defived from the SampleBase class. */

public struct SampleSubClass: Codable {

    public var subClassStringProp: String?
    public var subClassIntegerProp: Int?

    public init(subClassStringProp: String?, subClassIntegerProp: Int?) {
        self.subClassStringProp = subClassStringProp
        self.subClassIntegerProp = subClassIntegerProp
    }


}

