# #Qdrant API
#
#The version of the OpenAPI document: master
#Contact: andrey@vasnetsov.com
#Generated by: https://openapi-generator.tech
#Generator version: 7.25.0-SNAPSHOT
#

module Qdrant::Api
  class SearchMatrixRequest
    include JSON::Serializable
    include YAML::Serializable
    include Qdrant::Api::Serializable
    include Qdrant::Api::Validation

    # Optional properties
    # Specify in which shards to look for the points, if not specified - look in all shards
    @[JSON::Field(key: "shard_key", emit_null: false)]
    property shard_key : ShardKeySelector?

    # Look only for points which satisfies this conditions
    @[JSON::Field(key: "filter", emit_null: false)]
    property filter : Filter?

    # How many points to select and search within. Default is 10.
    @[JSON::Field(key: "sample", emit_null: false)]
    property sample : Int32?

    # How many neighbours per sample to find. Default is 3.
    @[JSON::Field(key: "limit", emit_null: false)]
    property limit : Int32?

    # Define which vector name to use for querying. If missing, the default vector is used.
    @[JSON::Field(key: "using", emit_null: false)]
    property using : String?

    validates(sample, Int32, true, minimum: 2)
    validates(limit, Int32, true, minimum: 1)

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(@shard_key : ShardKeySelector? = nil, @filter : Filter? = nil, @sample : Int32? = nil, @limit : Int32? = nil, @using : String? = nil)
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array(String).new
      if (msg = sample_validation_error(@sample))
        invalid_properties.push(msg)
      end
      if (msg = limit_validation_error(@limit))
        invalid_properties.push(msg)
      end
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      list_invalid_properties.empty?
    end

    def_equals_and_hash(shard_key, filter, sample, limit, using)
  end

end
