/*
 * OpenAPI Petstore
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.openapitools.client.model.FreeFormObjectTestClassProperties;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FreeFormObjectTestClass
 */
public class FreeFormObjectTestClassTest {
    private final FreeFormObjectTestClass model = new FreeFormObjectTestClass();

    /**
     * Model tests for FreeFormObjectTestClass
     */
    @Test
    public void testFreeFormObjectTestClass() {
        // TODO: test FreeFormObjectTestClass
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

}
