/**
* This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#pragma once
// System headers
#include <nlohmann/json.hpp>
#include <cstdint>
#include <string>



namespace models {


class CreatedResponse
{
public:

    CreatedResponse();
    virtual ~CreatedResponse() = default;

    // Getters and setters
    [[nodiscard]] std::string getStatus() const;
    void setStatus(const std::string& status);
    [[nodiscard]] int getId() const;
    void setId(const int& id);
    [[nodiscard]] std::string getLocation() const;
    void setLocation(const std::string& location);


    // JSON serialization using NLOHMANN INTRUSIVE macro (must be inside class to access private members)
    NLOHMANN_DEFINE_TYPE_INTRUSIVE(CreatedResponse,
         status, id, location)

private:
    std::string status;
    int id;
    std::string location;
};


} // namespace models

