/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 5.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UploadFileBody.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UploadFileBody_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UploadFileBody_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "HttpContent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  UploadFileBody
    : public ModelBase
{
public:
    UploadFileBody();
    virtual ~UploadFileBody();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UploadFileBody members

    /// <summary>
    /// Additional data to pass to server
    /// </summary>
    utility::string_t getAdditionalMetadata() const;
    bool additionalMetadataIsSet() const;
    void unsetAdditionalMetadata();

    void setAdditionalMetadata(const utility::string_t& value);

    /// <summary>
    /// file to upload
    /// </summary>
    std::shared_ptr<HttpContent> getFile() const;
    bool fileIsSet() const;
    void unsetfile();

    void setFile(const std::shared_ptr<HttpContent>& value);


protected:
    utility::string_t m_AdditionalMetadata;
    bool m_AdditionalMetadataIsSet;
    std::shared_ptr<HttpContent> m_file;
    bool m_fileIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UploadFileBody_H_ */
