/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Org.OpenAPITools.Client;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// MixLog
    /// </summary>
    [DataContract(Name = "MixLog")]
    public partial class MixLog : IEquatable<MixLog>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MixLog" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MixLog() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MixLog" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="mixDate">mixDate (required).</param>
        /// <param name="shopId">shopId.</param>
        /// <param name="totalPrice">totalPrice.</param>
        /// <param name="totalRecalculations">totalRecalculations (required).</param>
        /// <param name="totalOverPoors">totalOverPoors (required).</param>
        /// <param name="totalSkips">totalSkips (required).</param>
        /// <param name="totalUnderPours">totalUnderPours (required).</param>
        /// <param name="formulaVersionDate">formulaVersionDate (required).</param>
        /// <param name="someCode">SomeCode is only required for color mixes.</param>
        /// <param name="batchNumber">batchNumber.</param>
        /// <param name="brandCode">BrandCode is only required for non-color mixes.</param>
        /// <param name="brandId">BrandId is only required for color mixes.</param>
        /// <param name="brandName">BrandName is only required for color mixes.</param>
        /// <param name="categoryCode">CategoryCode is not used anymore.</param>
        /// <param name="color">Color is only required for color mixes.</param>
        /// <param name="colorDescription">colorDescription.</param>
        /// <param name="comment">comment.</param>
        /// <param name="commercialProductCode">commercialProductCode.</param>
        /// <param name="productLineCode">ProductLineCode is only required for color mixes.</param>
        /// <param name="country">country.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="createdByFirstName">createdByFirstName.</param>
        /// <param name="createdByLastName">createdByLastName.</param>
        /// <param name="deltaECalculationRepaired">deltaECalculationRepaired.</param>
        /// <param name="deltaECalculationSprayout">deltaECalculationSprayout.</param>
        /// <param name="ownColorVariantNumber">ownColorVariantNumber.</param>
        /// <param name="primerProductId">primerProductId.</param>
        /// <param name="productId">ProductId is only required for color mixes.</param>
        /// <param name="productName">ProductName is only required for color mixes.</param>
        /// <param name="selectedVersionIndex">selectedVersionIndex.</param>
        public MixLog(Guid id = default(Guid), string description = default(string), DateTime mixDate = default(DateTime), Option<Guid> shopId = default(Option<Guid>), Option<float?> totalPrice = default(Option<float?>), int totalRecalculations = default(int), int totalOverPoors = default(int), int totalSkips = default(int), int totalUnderPours = default(int), DateTime formulaVersionDate = default(DateTime), Option<string> someCode = default(Option<string>), Option<string> batchNumber = default(Option<string>), Option<string> brandCode = default(Option<string>), Option<string> brandId = default(Option<string>), Option<string> brandName = default(Option<string>), Option<string> categoryCode = default(Option<string>), Option<string> color = default(Option<string>), Option<string> colorDescription = default(Option<string>), Option<string> comment = default(Option<string>), Option<string> commercialProductCode = default(Option<string>), Option<string> productLineCode = default(Option<string>), Option<string> country = default(Option<string>), Option<string> createdBy = default(Option<string>), Option<string> createdByFirstName = default(Option<string>), Option<string> createdByLastName = default(Option<string>), Option<string> deltaECalculationRepaired = default(Option<string>), Option<string> deltaECalculationSprayout = default(Option<string>), Option<int?> ownColorVariantNumber = default(Option<int?>), Option<string> primerProductId = default(Option<string>), Option<string> productId = default(Option<string>), Option<string> productName = default(Option<string>), Option<int> selectedVersionIndex = default(Option<int>))
        {
            // to ensure "id" (not nullable) is not null
            if (id == null)
            {
                throw new ArgumentNullException("id isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "description" (not nullable) is not null
            if (description == null)
            {
                throw new ArgumentNullException("description isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "mixDate" (not nullable) is not null
            if (mixDate == null)
            {
                throw new ArgumentNullException("mixDate isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "shopId" (not nullable) is not null
            if (shopId.IsSet && shopId.Value == null)
            {
                throw new ArgumentNullException("shopId isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "formulaVersionDate" (not nullable) is not null
            if (formulaVersionDate == null)
            {
                throw new ArgumentNullException("formulaVersionDate isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "batchNumber" (not nullable) is not null
            if (batchNumber.IsSet && batchNumber.Value == null)
            {
                throw new ArgumentNullException("batchNumber isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "brandCode" (not nullable) is not null
            if (brandCode.IsSet && brandCode.Value == null)
            {
                throw new ArgumentNullException("brandCode isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "brandId" (not nullable) is not null
            if (brandId.IsSet && brandId.Value == null)
            {
                throw new ArgumentNullException("brandId isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "brandName" (not nullable) is not null
            if (brandName.IsSet && brandName.Value == null)
            {
                throw new ArgumentNullException("brandName isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "categoryCode" (not nullable) is not null
            if (categoryCode.IsSet && categoryCode.Value == null)
            {
                throw new ArgumentNullException("categoryCode isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "color" (not nullable) is not null
            if (color.IsSet && color.Value == null)
            {
                throw new ArgumentNullException("color isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "colorDescription" (not nullable) is not null
            if (colorDescription.IsSet && colorDescription.Value == null)
            {
                throw new ArgumentNullException("colorDescription isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "comment" (not nullable) is not null
            if (comment.IsSet && comment.Value == null)
            {
                throw new ArgumentNullException("comment isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "commercialProductCode" (not nullable) is not null
            if (commercialProductCode.IsSet && commercialProductCode.Value == null)
            {
                throw new ArgumentNullException("commercialProductCode isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "productLineCode" (not nullable) is not null
            if (productLineCode.IsSet && productLineCode.Value == null)
            {
                throw new ArgumentNullException("productLineCode isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "country" (not nullable) is not null
            if (country.IsSet && country.Value == null)
            {
                throw new ArgumentNullException("country isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "createdBy" (not nullable) is not null
            if (createdBy.IsSet && createdBy.Value == null)
            {
                throw new ArgumentNullException("createdBy isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "createdByFirstName" (not nullable) is not null
            if (createdByFirstName.IsSet && createdByFirstName.Value == null)
            {
                throw new ArgumentNullException("createdByFirstName isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "createdByLastName" (not nullable) is not null
            if (createdByLastName.IsSet && createdByLastName.Value == null)
            {
                throw new ArgumentNullException("createdByLastName isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "deltaECalculationRepaired" (not nullable) is not null
            if (deltaECalculationRepaired.IsSet && deltaECalculationRepaired.Value == null)
            {
                throw new ArgumentNullException("deltaECalculationRepaired isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "deltaECalculationSprayout" (not nullable) is not null
            if (deltaECalculationSprayout.IsSet && deltaECalculationSprayout.Value == null)
            {
                throw new ArgumentNullException("deltaECalculationSprayout isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "primerProductId" (not nullable) is not null
            if (primerProductId.IsSet && primerProductId.Value == null)
            {
                throw new ArgumentNullException("primerProductId isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "productId" (not nullable) is not null
            if (productId.IsSet && productId.Value == null)
            {
                throw new ArgumentNullException("productId isn't a nullable property for MixLog and cannot be null");
            }
            // to ensure "productName" (not nullable) is not null
            if (productName.IsSet && productName.Value == null)
            {
                throw new ArgumentNullException("productName isn't a nullable property for MixLog and cannot be null");
            }
            this.Id = id;
            this.Description = description;
            this.MixDate = mixDate;
            this.ShopId = shopId;
            this.TotalPrice = totalPrice;
            this.TotalRecalculations = totalRecalculations;
            this.TotalOverPoors = totalOverPoors;
            this.TotalSkips = totalSkips;
            this.TotalUnderPours = totalUnderPours;
            this.FormulaVersionDate = formulaVersionDate;
            this.SomeCode = someCode;
            this.BatchNumber = batchNumber;
            this.BrandCode = brandCode;
            this.BrandId = brandId;
            this.BrandName = brandName;
            this.CategoryCode = categoryCode;
            this.Color = color;
            this.ColorDescription = colorDescription;
            this.Comment = comment;
            this.CommercialProductCode = commercialProductCode;
            this.ProductLineCode = productLineCode;
            this.Country = country;
            this.CreatedBy = createdBy;
            this.CreatedByFirstName = createdByFirstName;
            this.CreatedByLastName = createdByLastName;
            this.DeltaECalculationRepaired = deltaECalculationRepaired;
            this.DeltaECalculationSprayout = deltaECalculationSprayout;
            this.OwnColorVariantNumber = ownColorVariantNumber;
            this.PrimerProductId = primerProductId;
            this.ProductId = productId;
            this.ProductName = productName;
            this.SelectedVersionIndex = selectedVersionIndex;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets MixDate
        /// </summary>
        [DataMember(Name = "mixDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime MixDate { get; set; }

        /// <summary>
        /// Gets or Sets ShopId
        /// </summary>
        [DataMember(Name = "shopId", EmitDefaultValue = false)]
        public Option<Guid> ShopId { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrice
        /// </summary>
        [DataMember(Name = "totalPrice", EmitDefaultValue = true)]
        public Option<float?> TotalPrice { get; set; }

        /// <summary>
        /// Gets or Sets TotalRecalculations
        /// </summary>
        [DataMember(Name = "totalRecalculations", IsRequired = true, EmitDefaultValue = true)]
        public int TotalRecalculations { get; set; }

        /// <summary>
        /// Gets or Sets TotalOverPoors
        /// </summary>
        [DataMember(Name = "totalOverPoors", IsRequired = true, EmitDefaultValue = true)]
        public int TotalOverPoors { get; set; }

        /// <summary>
        /// Gets or Sets TotalSkips
        /// </summary>
        [DataMember(Name = "totalSkips", IsRequired = true, EmitDefaultValue = true)]
        public int TotalSkips { get; set; }

        /// <summary>
        /// Gets or Sets TotalUnderPours
        /// </summary>
        [DataMember(Name = "totalUnderPours", IsRequired = true, EmitDefaultValue = true)]
        public int TotalUnderPours { get; set; }

        /// <summary>
        /// Gets or Sets FormulaVersionDate
        /// </summary>
        [DataMember(Name = "formulaVersionDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime FormulaVersionDate { get; set; }

        /// <summary>
        /// SomeCode is only required for color mixes
        /// </summary>
        /// <value>SomeCode is only required for color mixes</value>
        [DataMember(Name = "someCode", EmitDefaultValue = true)]
        public Option<string> SomeCode { get; set; }

        /// <summary>
        /// Gets or Sets BatchNumber
        /// </summary>
        [DataMember(Name = "batchNumber", EmitDefaultValue = false)]
        public Option<string> BatchNumber { get; set; }

        /// <summary>
        /// BrandCode is only required for non-color mixes
        /// </summary>
        /// <value>BrandCode is only required for non-color mixes</value>
        [DataMember(Name = "brandCode", EmitDefaultValue = false)]
        public Option<string> BrandCode { get; set; }

        /// <summary>
        /// BrandId is only required for color mixes
        /// </summary>
        /// <value>BrandId is only required for color mixes</value>
        [DataMember(Name = "brandId", EmitDefaultValue = false)]
        public Option<string> BrandId { get; set; }

        /// <summary>
        /// BrandName is only required for color mixes
        /// </summary>
        /// <value>BrandName is only required for color mixes</value>
        [DataMember(Name = "brandName", EmitDefaultValue = false)]
        public Option<string> BrandName { get; set; }

        /// <summary>
        /// CategoryCode is not used anymore
        /// </summary>
        /// <value>CategoryCode is not used anymore</value>
        [DataMember(Name = "categoryCode", EmitDefaultValue = false)]
        public Option<string> CategoryCode { get; set; }

        /// <summary>
        /// Color is only required for color mixes
        /// </summary>
        /// <value>Color is only required for color mixes</value>
        [DataMember(Name = "color", EmitDefaultValue = false)]
        public Option<string> Color { get; set; }

        /// <summary>
        /// Gets or Sets ColorDescription
        /// </summary>
        [DataMember(Name = "colorDescription", EmitDefaultValue = false)]
        public Option<string> ColorDescription { get; set; }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name = "comment", EmitDefaultValue = false)]
        public Option<string> Comment { get; set; }

        /// <summary>
        /// Gets or Sets CommercialProductCode
        /// </summary>
        [DataMember(Name = "commercialProductCode", EmitDefaultValue = false)]
        public Option<string> CommercialProductCode { get; set; }

        /// <summary>
        /// ProductLineCode is only required for color mixes
        /// </summary>
        /// <value>ProductLineCode is only required for color mixes</value>
        [DataMember(Name = "productLineCode", EmitDefaultValue = false)]
        public Option<string> ProductLineCode { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public Option<string> Country { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name = "createdBy", EmitDefaultValue = false)]
        public Option<string> CreatedBy { get; set; }

        /// <summary>
        /// Gets or Sets CreatedByFirstName
        /// </summary>
        [DataMember(Name = "createdByFirstName", EmitDefaultValue = false)]
        public Option<string> CreatedByFirstName { get; set; }

        /// <summary>
        /// Gets or Sets CreatedByLastName
        /// </summary>
        [DataMember(Name = "createdByLastName", EmitDefaultValue = false)]
        public Option<string> CreatedByLastName { get; set; }

        /// <summary>
        /// Gets or Sets DeltaECalculationRepaired
        /// </summary>
        [DataMember(Name = "deltaECalculationRepaired", EmitDefaultValue = false)]
        public Option<string> DeltaECalculationRepaired { get; set; }

        /// <summary>
        /// Gets or Sets DeltaECalculationSprayout
        /// </summary>
        [DataMember(Name = "deltaECalculationSprayout", EmitDefaultValue = false)]
        public Option<string> DeltaECalculationSprayout { get; set; }

        /// <summary>
        /// Gets or Sets OwnColorVariantNumber
        /// </summary>
        [DataMember(Name = "ownColorVariantNumber", EmitDefaultValue = true)]
        public Option<int?> OwnColorVariantNumber { get; set; }

        /// <summary>
        /// Gets or Sets PrimerProductId
        /// </summary>
        [DataMember(Name = "primerProductId", EmitDefaultValue = false)]
        public Option<string> PrimerProductId { get; set; }

        /// <summary>
        /// ProductId is only required for color mixes
        /// </summary>
        /// <value>ProductId is only required for color mixes</value>
        [DataMember(Name = "productId", EmitDefaultValue = false)]
        public Option<string> ProductId { get; set; }

        /// <summary>
        /// ProductName is only required for color mixes
        /// </summary>
        /// <value>ProductName is only required for color mixes</value>
        [DataMember(Name = "productName", EmitDefaultValue = false)]
        public Option<string> ProductName { get; set; }

        /// <summary>
        /// Gets or Sets SelectedVersionIndex
        /// </summary>
        [DataMember(Name = "selectedVersionIndex", EmitDefaultValue = false)]
        public Option<int> SelectedVersionIndex { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MixLog {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MixDate: ").Append(MixDate).Append("\n");
            sb.Append("  ShopId: ").Append(ShopId).Append("\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  TotalRecalculations: ").Append(TotalRecalculations).Append("\n");
            sb.Append("  TotalOverPoors: ").Append(TotalOverPoors).Append("\n");
            sb.Append("  TotalSkips: ").Append(TotalSkips).Append("\n");
            sb.Append("  TotalUnderPours: ").Append(TotalUnderPours).Append("\n");
            sb.Append("  FormulaVersionDate: ").Append(FormulaVersionDate).Append("\n");
            sb.Append("  SomeCode: ").Append(SomeCode).Append("\n");
            sb.Append("  BatchNumber: ").Append(BatchNumber).Append("\n");
            sb.Append("  BrandCode: ").Append(BrandCode).Append("\n");
            sb.Append("  BrandId: ").Append(BrandId).Append("\n");
            sb.Append("  BrandName: ").Append(BrandName).Append("\n");
            sb.Append("  CategoryCode: ").Append(CategoryCode).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  ColorDescription: ").Append(ColorDescription).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  CommercialProductCode: ").Append(CommercialProductCode).Append("\n");
            sb.Append("  ProductLineCode: ").Append(ProductLineCode).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedByFirstName: ").Append(CreatedByFirstName).Append("\n");
            sb.Append("  CreatedByLastName: ").Append(CreatedByLastName).Append("\n");
            sb.Append("  DeltaECalculationRepaired: ").Append(DeltaECalculationRepaired).Append("\n");
            sb.Append("  DeltaECalculationSprayout: ").Append(DeltaECalculationSprayout).Append("\n");
            sb.Append("  OwnColorVariantNumber: ").Append(OwnColorVariantNumber).Append("\n");
            sb.Append("  PrimerProductId: ").Append(PrimerProductId).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  ProductName: ").Append(ProductName).Append("\n");
            sb.Append("  SelectedVersionIndex: ").Append(SelectedVersionIndex).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MixLog);
        }

        /// <summary>
        /// Returns true if MixLog instances are equal
        /// </summary>
        /// <param name="input">Instance of MixLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MixLog input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.MixDate == input.MixDate ||
                    (this.MixDate != null &&
                    this.MixDate.Equals(input.MixDate))
                ) && 
                (
                    
                    this.ShopId.Equals(input.ShopId)
                ) && 
                (
                    this.TotalPrice.Equals(input.TotalPrice)
                ) && 
                (
                    this.TotalRecalculations == input.TotalRecalculations ||
                    this.TotalRecalculations.Equals(input.TotalRecalculations)
                ) && 
                (
                    this.TotalOverPoors == input.TotalOverPoors ||
                    this.TotalOverPoors.Equals(input.TotalOverPoors)
                ) && 
                (
                    this.TotalSkips == input.TotalSkips ||
                    this.TotalSkips.Equals(input.TotalSkips)
                ) && 
                (
                    this.TotalUnderPours == input.TotalUnderPours ||
                    this.TotalUnderPours.Equals(input.TotalUnderPours)
                ) && 
                (
                    this.FormulaVersionDate == input.FormulaVersionDate ||
                    (this.FormulaVersionDate != null &&
                    this.FormulaVersionDate.Equals(input.FormulaVersionDate))
                ) && 
                (
                    
                    this.SomeCode.Equals(input.SomeCode)
                ) && 
                (
                    
                    this.BatchNumber.Equals(input.BatchNumber)
                ) && 
                (
                    
                    this.BrandCode.Equals(input.BrandCode)
                ) && 
                (
                    
                    this.BrandId.Equals(input.BrandId)
                ) && 
                (
                    
                    this.BrandName.Equals(input.BrandName)
                ) && 
                (
                    
                    this.CategoryCode.Equals(input.CategoryCode)
                ) && 
                (
                    
                    this.Color.Equals(input.Color)
                ) && 
                (
                    
                    this.ColorDescription.Equals(input.ColorDescription)
                ) && 
                (
                    
                    this.Comment.Equals(input.Comment)
                ) && 
                (
                    
                    this.CommercialProductCode.Equals(input.CommercialProductCode)
                ) && 
                (
                    
                    this.ProductLineCode.Equals(input.ProductLineCode)
                ) && 
                (
                    
                    this.Country.Equals(input.Country)
                ) && 
                (
                    
                    this.CreatedBy.Equals(input.CreatedBy)
                ) && 
                (
                    
                    this.CreatedByFirstName.Equals(input.CreatedByFirstName)
                ) && 
                (
                    
                    this.CreatedByLastName.Equals(input.CreatedByLastName)
                ) && 
                (
                    
                    this.DeltaECalculationRepaired.Equals(input.DeltaECalculationRepaired)
                ) && 
                (
                    
                    this.DeltaECalculationSprayout.Equals(input.DeltaECalculationSprayout)
                ) && 
                (
                    this.OwnColorVariantNumber.Equals(input.OwnColorVariantNumber)
                ) && 
                (
                    
                    this.PrimerProductId.Equals(input.PrimerProductId)
                ) && 
                (
                    
                    this.ProductId.Equals(input.ProductId)
                ) && 
                (
                    
                    this.ProductName.Equals(input.ProductName)
                ) && 
                (
                    this.SelectedVersionIndex.Equals(input.SelectedVersionIndex)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.MixDate != null)
                {
                    hashCode = (hashCode * 59) + this.MixDate.GetHashCode();
                }
                if (this.ShopId.IsSet && this.ShopId.Value != null)
                {
                    hashCode = (hashCode * 59) + this.ShopId.Value.GetHashCode();
                }
                if (this.TotalPrice.IsSet)
                {
                hashCode = (hashCode * 59) + this.TotalPrice.Value.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.TotalRecalculations.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalOverPoors.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalSkips.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalUnderPours.GetHashCode();
                if (this.FormulaVersionDate != null)
                {
                    hashCode = (hashCode * 59) + this.FormulaVersionDate.GetHashCode();
                }
                if (this.SomeCode.IsSet && this.SomeCode.Value != null)
                {
                    hashCode = (hashCode * 59) + this.SomeCode.Value.GetHashCode();
                }
                if (this.BatchNumber.IsSet && this.BatchNumber.Value != null)
                {
                    hashCode = (hashCode * 59) + this.BatchNumber.Value.GetHashCode();
                }
                if (this.BrandCode.IsSet && this.BrandCode.Value != null)
                {
                    hashCode = (hashCode * 59) + this.BrandCode.Value.GetHashCode();
                }
                if (this.BrandId.IsSet && this.BrandId.Value != null)
                {
                    hashCode = (hashCode * 59) + this.BrandId.Value.GetHashCode();
                }
                if (this.BrandName.IsSet && this.BrandName.Value != null)
                {
                    hashCode = (hashCode * 59) + this.BrandName.Value.GetHashCode();
                }
                if (this.CategoryCode.IsSet && this.CategoryCode.Value != null)
                {
                    hashCode = (hashCode * 59) + this.CategoryCode.Value.GetHashCode();
                }
                if (this.Color.IsSet && this.Color.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Color.Value.GetHashCode();
                }
                if (this.ColorDescription.IsSet && this.ColorDescription.Value != null)
                {
                    hashCode = (hashCode * 59) + this.ColorDescription.Value.GetHashCode();
                }
                if (this.Comment.IsSet && this.Comment.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Comment.Value.GetHashCode();
                }
                if (this.CommercialProductCode.IsSet && this.CommercialProductCode.Value != null)
                {
                    hashCode = (hashCode * 59) + this.CommercialProductCode.Value.GetHashCode();
                }
                if (this.ProductLineCode.IsSet && this.ProductLineCode.Value != null)
                {
                    hashCode = (hashCode * 59) + this.ProductLineCode.Value.GetHashCode();
                }
                if (this.Country.IsSet && this.Country.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Country.Value.GetHashCode();
                }
                if (this.CreatedBy.IsSet && this.CreatedBy.Value != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedBy.Value.GetHashCode();
                }
                if (this.CreatedByFirstName.IsSet && this.CreatedByFirstName.Value != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedByFirstName.Value.GetHashCode();
                }
                if (this.CreatedByLastName.IsSet && this.CreatedByLastName.Value != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedByLastName.Value.GetHashCode();
                }
                if (this.DeltaECalculationRepaired.IsSet && this.DeltaECalculationRepaired.Value != null)
                {
                    hashCode = (hashCode * 59) + this.DeltaECalculationRepaired.Value.GetHashCode();
                }
                if (this.DeltaECalculationSprayout.IsSet && this.DeltaECalculationSprayout.Value != null)
                {
                    hashCode = (hashCode * 59) + this.DeltaECalculationSprayout.Value.GetHashCode();
                }
                if (this.OwnColorVariantNumber.IsSet)
                {
                hashCode = (hashCode * 59) + this.OwnColorVariantNumber.Value.GetHashCode();
                }
                if (this.PrimerProductId.IsSet && this.PrimerProductId.Value != null)
                {
                    hashCode = (hashCode * 59) + this.PrimerProductId.Value.GetHashCode();
                }
                if (this.ProductId.IsSet && this.ProductId.Value != null)
                {
                    hashCode = (hashCode * 59) + this.ProductId.Value.GetHashCode();
                }
                if (this.ProductName.IsSet && this.ProductName.Value != null)
                {
                    hashCode = (hashCode * 59) + this.ProductName.Value.GetHashCode();
                }
                if (this.SelectedVersionIndex.IsSet)
                {
                hashCode = (hashCode * 59) + this.SelectedVersionIndex.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
