/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Category
import org.openapitools.client.models.Tag

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A pet for sale in the pet store
 *
 * @param name 
 * @param photoUrls 
 * @param id 
 * @param category 
 * @param tags 
 * @param status pet status in the store
 */


data class Pet (

    @get:JsonProperty("name")
    val name: String,

    @get:JsonProperty("photoUrls")
    val photoUrls: kotlin.collections.List<String>,

    @get:JsonProperty("id")
    val id: Long? = null,

    @get:JsonProperty("category")
    val category: Category? = null,

    @get:JsonProperty("tags")
    val tags: List<Tag>? = null,

    /* pet status in the store */
    @get:JsonProperty("status")
    val status: Pet.Status? = null

) {

    /**
     * pet status in the store
     *
     * Values: AVAILABLE,PENDING,SOLD,UNKNOWN_DEFAULT_OPEN_API
     */
    enum class Status(val value: String) {
        @JsonProperty(value = "available") AVAILABLE("available"),
        @JsonProperty(value = "pending") PENDING("pending"),
        @JsonProperty(value = "sold") SOLD("sold"),
        @JsonProperty(value = "unknown_default_open_api") @JsonEnumDefaultValue UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");
    }

}

