source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwaggerClient_Example', :exclusive => true do
  pod "SwaggerClient", :path => "../"
end

target 'SwaggerClient_Tests', :exclusive => true do
  pod "SwaggerClient", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
