# frozen_string_literal: true

# Qdrant API
#
# The version of the OpenAPI document: master
# Contact: andrey@vasnetsov.com
# Generated by OpenAPI Generator (https://openapi-generator.tech)

module Qdrant
  module Models
    module PayloadSchemaType
      KEYWORD = 'keyword'
      INTEGER = 'integer'
      FLOAT = 'float'
      GEO = 'geo'
      TEXT = 'text'
      BOOL = 'bool'
      DATETIME = 'datetime'
      UUID = 'uuid'

      def self.all
        @all ||= [
          KEYWORD,
          INTEGER,
          FLOAT,
          GEO,
          TEXT,
          BOOL,
          DATETIME,
          UUID,
        ].freeze
      end

      def self.valid?(value)
        all.include?(value)
      end
    end
  end
end
