/*
 * dummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.SchemaA;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostRequest
 */
public class PostRequestTest {
    private final PostRequest model = new PostRequest();

    /**
     * Model tests for PostRequest
     */
    @Test
    public void testPostRequest() {
        // TODO: test PostRequest
    }

    /**
     * Test the property 'propA'
     */
    @Test
    public void propATest() {
        // TODO: test propA
    }

}
