//
// EnumTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EnumTest: Codable, Hashable {

    public enum EnumString: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum EnumStringRequired: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum EnumInteger: Int, Codable, CaseIterable {
        case _1 = 1
        case number1 = -1
    }
    public enum EnumNumber: Double, Codable, CaseIterable {
        case _11 = 1.1
        case number12 = -1.2
    }
    public var enumString: EnumString?
    public var enumStringRequired: EnumStringRequired
    public var enumInteger: EnumInteger?
    public var enumNumber: EnumNumber?
    public var outerEnum: OuterEnum?

    public init(enumString: EnumString? = nil, enumStringRequired: EnumStringRequired, enumInteger: EnumInteger? = nil, enumNumber: EnumNumber? = nil, outerEnum: OuterEnum? = nil) {
        self.enumString = enumString
        self.enumStringRequired = enumStringRequired
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enumString = "enum_string"
        case enumStringRequired = "enum_string_required"
        case enumInteger = "enum_integer"
        case enumNumber = "enum_number"
        case outerEnum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let enumString = enumString {
            try container.encode(enumString, forKey: .enumString)
        } else {
            try container.encodeNil(forKey: .enumString)
        }
        try container.encode(enumStringRequired, forKey: .enumStringRequired)
        if let enumInteger = enumInteger {
            try container.encode(enumInteger, forKey: .enumInteger)
        } else {
            try container.encodeNil(forKey: .enumInteger)
        }
        if let enumNumber = enumNumber {
            try container.encode(enumNumber, forKey: .enumNumber)
        } else {
            try container.encodeNil(forKey: .enumNumber)
        }
        if let outerEnum = outerEnum {
            try container.encode(outerEnum, forKey: .outerEnum)
        } else {
            try container.encodeNil(forKey: .outerEnum)
        }
    }
}

