/**
 * Petstore Server
 * Sample petstore server for the cpp-boost-beast-server generator
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.26.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Error.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_SERVER_MODEL_Error_MODEL_H_
#define ORG_OPENAPITOOLS_SERVER_MODEL_Error_MODEL_H_

#include <string>
#include <vector>
#include <memory>
#include <boost/json.hpp>
#include "NullableField.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {



/// <summary>
/// 
/// </summary>
class Error
{
public:
    Error() = default;
    explicit Error(boost::json::value const& value);
    virtual ~Error() = default;

    std::string toJsonString(bool prettyJson = false) const;
    void fromJsonString(std::string const& jsonString);
    boost::json::value toJsonValue() const;
    void fromJsonValue(boost::json::value const& value);

    /////////////////////////////////////////////
    /// Error members

    /// <summary>
    /// 
    /// </summary>
    std::int32_t getCode() const;
    void setCode(std::int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::string getMessage() const;
    void setMessage(std::string value);

protected:
    //////////////////////////////////////
    // Override these for customization //
    //////////////////////////////////////

    virtual boost::json::object toJsonObject_internal() const;
    virtual void fromJsonObject_internal(boost::json::object const& object);


protected:
    std::int32_t m_Code = 0;
    std::string m_Message = "";
};

std::string createJsonStringFromModelVector(const std::vector<std::shared_ptr<Error>>& data);

void createModelVectorFromJsonString(std::vector<std::shared_ptr<Error>>& vec, const std::string& json);

Error fromJsonValue_Error(boost::json::value const& value);

}
}
}
}
#endif /* ORG_OPENAPITOOLS_SERVER_MODEL_Error_MODEL_H_ */
