{-
   OpenAPI Petstore
   This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.OuterComposite exposing (OuterComposite, decoder, encoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias OuterComposite =
    { my_number : Maybe Float
    , my_string : Maybe String
    , my_boolean : Maybe Bool
    }


decoder : Decoder OuterComposite
decoder =
    Decode.succeed OuterComposite
        |> optional "my_number" (Decode.nullable Decode.float) Nothing
        |> optional "my_string" (Decode.nullable Decode.string) Nothing
        |> optional "my_boolean" (Decode.nullable Decode.bool) Nothing


encoder : OuterComposite -> Encode.Value
encoder model =
    Encode.object
        [ ( "my_number", Maybe.withDefault Encode.null (Maybe.map Encode.float model.my_number) )
        , ( "my_string", Maybe.withDefault Encode.null (Maybe.map Encode.string model.my_string) )
        , ( "my_boolean", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.my_boolean) )
        ]
