{-
   OpenAPI Petstore
   This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\

   OpenAPI spec version: 1.0.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.SpecialModelName exposing (SpecialModelName, decoder, encoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias SpecialModelName =
    { nSpecial_property_name_ : Maybe Int
    }


decoder : Decoder SpecialModelName
decoder =
    Decode.succeed SpecialModelName
        |> optional "$special[property.name]" (Decode.nullable Decode.int) Nothing


encoder : SpecialModelName -> Encode.Value
encoder model =
    Encode.object
        [ ( "$special[property.name]", Maybe.withDefault Encode.null (Maybe.map Encode.int model.nSpecial_property_name_) )
        ]
