platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'TestClientApp' do
    pod "TestClient", :path => "../"

    target 'TestClientAppTests' do
        inherit! :search_paths
    end
end
