import Vue from 'vue'
import App from './App'
import router from './router'
import VueTreeNavigation from 'vue-tree-navigation'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import {
  faBullhorn,
  faUniversalAccess,
  faQuestionCircle,
  faMapMarkedAlt,
  faProjectDiagram,
  faUsersCog,
  faGlobe,
  faFileInvoice,
  faFileSignature,
  faShareSquare,
  faLightbulb,
  faSitemap,
  faUsers,
  faEnvelopeSquare,
  faEnvelope,
  faTimes,
  faThList,
  faHandshake,
  faEdit,
  faSearch,
  faMicroscope,
  faComments,
  faLanguage,
  faPeopleCarry,
  faBug,
  faUserClock,
  faPaperclip,
  faBell,
  faClipboard,
  faHeadset,
  faUserTie,
  faIdCard,
  faExclamationTriangle,
  faCogs,
  faSlidersH,
  faBook,
  faFileAlt,
  faThLarge,
  faCopy,
  faArchway,
  faBolt,
  faDesktop,
  faChartBar,
  faDatabase,
  faRetweet,
  faHeart,
  faWrench,
  faColumns,
  faPaperPlane,
  faExchangeAlt,
  faKey,
  faThumbsUp,
  faThumbsDown,
  faPaste,
  faLink,
  faBookReader,
  faRobot,
  faTaxi,
  faCubes,
  faPencilAlt,
  faSignal,
  faCheck,
  faFileWord,
  faPlusSquare,
  faMapSigns,
  faBox,
  faUser,
  faBirthdayCake,
  faBuilding,
  faCommentAlt,
  faChartArea,
  faHandsHelping,
  faBoxes,
  faFire,
  faAward,
  faGraduationCap,
  faPhoneSquare,
  faTasks,
  faMousePointer,
  faWindowClose,
  faClone,
  faChartLine,
  faFlag
} from '@fortawesome/free-solid-svg-icons'

Vue.use(VueTreeNavigation)
library.add(
  faBullhorn,
  faUniversalAccess,
  faQuestionCircle,
  faMapMarkedAlt,
  faProjectDiagram,
  faUsersCog,
  faGlobe,
  faFileInvoice,
  faFileSignature,
  faShareSquare,
  faLightbulb,
  faSitemap,
  faUsers,
  faEnvelopeSquare,
  faEnvelope,
  faTimes,
  faThList,
  faHandshake,
  faEdit,
  faSearch,
  faMicroscope,
  faComments,
  faLanguage,
  faPeopleCarry,
  faBug,
  faUserClock,
  faPaperclip,
  faBell,
  faClipboard,
  faHeadset,
  faUserTie,
  faIdCard,
  faExclamationTriangle,
  faCogs,
  faSlidersH,
  faBook,
  faFileAlt,
  faThLarge,
  faCopy,
  faArchway,
  faBolt,
  faDesktop,
  faChartBar,
  faDatabase,
  faRetweet,
  faHeart,
  faWrench,
  faColumns,
  faPaperPlane,
  faExchangeAlt,
  faKey,
  faThumbsUp,
  faThumbsDown,
  faPaste,
  faLink,
  faBookReader,
  faRobot,
  faTaxi,
  faCubes,
  faPencilAlt,
  faSignal,
  faCheck,
  faFileWord,
  faPlusSquare,
  faMapSigns,
  faBox,
  faUser,
  faBirthdayCake,
  faBuilding,
  faCommentAlt,
  faChartArea,
  faHandsHelping,
  faBoxes,
  faFire,
  faAward,
  faGraduationCap,
  faPhoneSquare,
  faTasks,
  faMousePointer,
  faWindowClose,
  faClone,
  faChartLine,
  faFlag
)

const filter = (text, length, clamp) => {
  clamp = clamp || '...'
  var node = document.createElement('div')
  node.innerHTML = text
  var content = node.textContent
  return content.length > length ? content.slice(0, length) + clamp : content
}

Vue.filter('truncate', filter)

Vue.component('font-awesome-icon', FontAwesomeIcon)
Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  render: h => h(App)
})
