# Maven CI build for the smals-belgium openapi-generator
name: Maven build and publish snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Update group id
        uses: ./.github/actions/update-group-id
        with:
          old-group-id: org.openapitools
          new-group-id: io.github.smals-belgium

      - name: Update artifact version
        run: |
          VERSION=${{ github.event_name == 'pull_request' && format('pr{0}-SNAPSHOT', github.event.pull_request.number) || 'latest-SNAPSHOT' }}
          mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

      - name: Build and publish with Maven
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}