name: Samples Ruby Idiomatic

on:
  push:
    paths:
      - 'samples/client/petstore/ruby-idiomatic/**'
      - 'samples/client/others/ruby-idiomatic-qdrant/**'
  pull_request:
    paths:
      - 'samples/client/petstore/ruby-idiomatic/**'
      - 'samples/client/others/ruby-idiomatic-qdrant/**'

jobs:
  build:
    name: Build Ruby Idiomatic client
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample:
          - samples/client/petstore/ruby-idiomatic
        ruby-version:
          - '3.0'
          - '3.3'
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install and test
        working-directory: ${{ matrix.sample }}
        run: |
          bundle install
          bundle exec rspec
